import Footer from "@/components/layout/footer/footer";
import Header from "@/components/layout/header/header";
import layoutStyles from '@/components/layout/layout.module.css';
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "mumemo",
  description: "Generated by create next app",
};
// TODO:クライアントコンポーネントで閲覧数をカウントするためのコンポーネントを作成する
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <div className={layoutStyles.grid}>
          <Header />
          {children}
          <Footer />
          <SpeedInsights />
          <Analytics />
        </div>
      </body>
    </html>
  );
}
